# Copyright 2019 Google LLC
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.

language: cpp

# Use container-based image; it usually starts up faster.
sudo: false

# Don't run CI on non-master branches (does not affect PRs).
branches:
  only:
  - master

matrix:
  include:

    - os: linux
      env: C_COMPILER=clang-6.0 CXX_COMPILER=clang++-6.0
      addons:
        apt:
          sources:
          - llvm-toolchain-trusty-6.0
          - ubuntu-toolchain-r-test
          packages:
          - clang-6.0
          - libstdc++-8-dev

    - os: linux
      env: C_COMPILER=clang-7 CXX_COMPILER=clang++-7
      addons:
        apt:
          sources:
          - llvm-toolchain-trusty-7
          - ubuntu-toolchain-r-test
          packages:
          - clang-7
          - libstdc++-8-dev

before_install:
- if [ -n "${C_COMPILER}" ]; then export CC="${C_COMPILER}"; fi
- if [ -n "${CXX_COMPILER}" ]; then export CXX="${CXX_COMPILER}"; fi

script:
  - make
