image: Visual Studio 2017
configuration: Release

install:
    - git submodule update --init
    - cmake . -A x64

build:
  project: pik.sln

artifacts:
    - path: bin\**\cpik.exe
      name: cpik
    - path: bin\**\dpik.exe
      name: dpik

deploy:
  - provider: GitHub
    artifact: $(APPVEYOR_PROJECT_NAME)
    auth_token:
      secure: 'hY5Mk6KOwgQ97TzEBsM7Woqr1ZIm5QTvHg8EvxMV1x8j3wk/3mNBMqWFFbEIBK0i'
    prerelease: true
    on:
      appveyor_repo_tag: true
